version: '{build}'
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
init:
- ps: git config --global core.autocrlf true
environment:
  VisualStudioVersion: 15.0
nuget:
  disable_publish_on_pr: true
build_script:
- ps: Build\build.ps1
test: off
artifacts:
- path: Publish\*.nupkg
  name: NuGet Package